# Swagger
version=1.0.0
title=External Occurrences API
schemes=http
host=localhost:8080
basePath=/externalOccurrences-api/api
resourcePackage=com.strandls.externalOccurrences
prettyPrint=true
scan=true

# GBIF
gbif_parquet_path=/home/prakhar/workspace/gbif-cca/gbif-occurrence-with-iucn-and-species-group-updated-with-link-updated.parquet
gbif_point_padding=0.1

# DuckDB
duckdb_database_path=/home/prakhar/workspace/gbif-cca/external_occurrences.db
duckdb_memory_limit=50MB
duckdb_temp_directory=/home/prakhar/workspace/gbif-cca/duckdb_temp
